version: '3.8'

services:
  web:
    build: .
    container_name: pulse-care-app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - REDIS_HOST=pulse-care-redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: pulse-care-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data: